name: moodymuch
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # if you are using latest flutter please update your flutter_svg package to ^0.18.*
  flutter_svg: ^0.19.1 # help us to use SVG in our app
  provider: ^4.3.1 # for State management
  flutter_spinkit: "^4.0.0"
  flutter_markdown: ^0.4.1
  google_fonts: any

  firebase_core: ^0.5.1
  firebase_auth: ^0.18.1
  cloud_firestore: ^0.14.1
  firebase_storage: ^5.2.0
  http: ^0.12.0+2
  youtube_player_flutter: ^6.0.3+2

  flutter_facebook_login: ^3.0.0
  flutter_twitter_login: ^1.1.0
  google_sign_in: ^4.5.9

  image_picker: ^0.6.3
  settings_ui: ^0.6.0
  csc_picker: ^0.1.0
  percent_indicator: ^3.0.1
  animations: ^2.0.0
  dio: ^3.0.9
  url_launcher: ^6.0.3
  rxdart: ^0.23.1
  bloc: ^3.0.0
  audioplayers: 

  intl: ^0.16.1
  intl_phone_field: ^2.0.0
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.3
  syncfusion_flutter_charts: ^18.4.49

  logger: ^1.0.0

  tuple: ^1.0.3

  image: ^2.1.10 # ^2.1.19
  toast: ^0.1.5
  mailer: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/policies/
    - assets/songs/
    - assets/models/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
